[32m2024-11-27 21:23:40 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a47f4a8e-d5e3-4e02-8b4f-78e2f4f5cd5c - 18670 - LOGS_CAPTURED - Started capturing logs in process (pid: 18670).
[32m2024-11-27 21:23:40 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a47f4a8e-d5e3-4e02-8b4f-78e2f4f5cd5c - 18670 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2024-11-27 21:23:42 -0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a47f4a8e-d5e3-4e02-8b4f-78e2f4f5cd5c - 18670 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/opt/homebrew/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/opt/homebrew/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
  File "/opt/homebrew/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/opt/homebrew/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/dagster_university/dagster_university/assets/trips.py", line 15, in taxi_trips_file
    with open(constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb") as output_file:
[0m
