[32m2024-11-30 15:32:46 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6c136cd1-ad11-455d-8eef-755ec6ac3fa6 - 37206 - LOGS_CAPTURED - Started capturing logs in process (pid: 37206).
[32m2024-11-30 15:32:46 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6c136cd1-ad11-455d-8eef-755ec6ac3fa6 - 37206 - manhattan_stats - STEP_START - Started execution of step "manhattan_stats".
[32m2024-11-30 15:32:46 -0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 6c136cd1-ad11-455d-8eef-755ec6ac3fa6 - 37206 - manhattan_stats - STEP_FAILURE - Execution of step "manhattan_stats" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "manhattan_stats"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name zones does not exist!
Did you mean "pg_namespace"?
LINE 8:         left join zones on trips.pickup_zone_id = zones.zone_id
        where borough = 'Manhattan' and geometry is not null
        group by zone, borough, geometry
    ...
                          ^

Stack Trace:
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/dagster_university/dagster_university/assets/metrics.py", line 29, in manhattan_stats
    trips_by_zone = conn.execute(query).fetch_df()
                    ^^^^^^^^^^^^^^^^^^^
[0m
