[32m2024-11-30 15:35:34 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 04cff63b-d10b-4839-9d77-42677f6d0c35 - 37345 - LOGS_CAPTURED - Started capturing logs in process (pid: 37345).
[32m2024-11-30 15:35:34 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 04cff63b-d10b-4839-9d77-42677f6d0c35 - 37345 - taxi_zones - STEP_START - Started execution of step "taxi_zones".
[32m2024-11-30 15:35:34 -0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 04cff63b-d10b-4839-9d77-42677f6d0c35 - 37345 - taxi_zones - STEP_FAILURE - Execution of step "taxi_zones" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_zones"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name {constants.TAXI_ZONES_FILE_PATH} does not exist!
Did you mean "pg_class"?
LINE 8:           from '{constants.TAXI_ZONES_FILE_PATH}'
                       ^

Stack Trace:
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jairusmartinez/Documents/Python_Data_Analysis/dagsteru/dagster_university/dagster_university/assets/trips.py", line 78, in taxi_zones
    conn.execute(sql_query)
[0m
